### ISSUE TITLE
World whitelist not working

### ISSUE THREAD

**Issue by Drc-DEV** [ryandw11/UltraBar#9]
```
BossBarMessages:
  Enabled: true
  World_Whitelist_Enabled: true
  Random_Order: false
  World_Whitelist:
  - world
  Number_Of_Messages: 1
  '1':
    Message: '&fTest msg'
    Color: green
    Style: '1'
    Time: 15
```

With this configuration, the bossbar message appears on every world, regardless from the whitelist put in config.
